export const POPULAR_MOVIES = [
  {
    backdrop_path: "/pxJbfnMIQQxCrdeLD0zQnWr6ouL.jpg",
    genre_ids: [28, 35, 53],
    id: 1077280,
    original_title: "Die Hart",
    overview:
      "Follow a fictionalized version of Kevin Hart, as he tries to become an action movie star. He attends a school run by Ron Wilcox, where he attempts to learn the ropes on how to become one of the industry's most coveted action stars.",
    poster_path: "/1EnBjTJ5utgT1OXYBZ8YwByRCzP.jpg",
    release_date: "2023-02-22",
    title: "Die Hart",
    vote_average: 6.3,
  },
  {
    backdrop_path: "/22z44LPkMyf5nyyXvv8qQLsbom.jpg",
    genre_ids: [27, 9648, 53],
    id: 631842,
    original_title: "Knock at the Cabin",
    overview:
      "While vacationing at a remote cabin, a young girl and her two fathers are taken hostage by four armed strangers who demand that the family make an unthinkable choice to avert the apocalypse. With limited access to the outside world, the family must decide what they believe before all is lost.",
    poster_path: "/dm06L9pxDOL9jNSK4Cb6y139rrG.jpg",
    release_date: "2023-02-01",
    title: "Knock at the Cabin",
    vote_average: 6.5,
  },
  {
    backdrop_path: "/jr8tSoJGj33XLgFBy6lmZhpGQNu.jpg",
    genre_ids: [16, 12, 35, 10751],
    id: 315162,
    original_title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    release_date: "2022-12-07",
    title: "Puss in Boots: The Last Wish",
    vote_average: 8.4,
  },
  {
    backdrop_path: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
    genre_ids: [28, 12, 878],
    id: 505642,
    original_title: "Black Panther: Wakanda Forever",
    overview:
      "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
    poster_path: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    release_date: "2022-11-09",
    title: "Black Panther: Wakanda Forever",
    vote_average: 7.3,
  },
  {
    backdrop_path: "/AsEgGeccI32SwMBkxpwhOkhbzmF.jpg",
    genre_ids: [28, 878, 53, 27],
    id: 1011679,
    original_title: "Shark Side of the Moon",
    overview:
      "Decades ago, the USSR developed unkillable sharks and launched them to the moon. Today, a team of American astronauts will endure the fight of their lives.",
    poster_path: "/v5CfpzxoJDkZxjZAizClFdlEF0U.jpg",
    release_date: "2022-08-12",
    title: "Shark Side of the Moon",
    vote_average: 5.4,
  },
  {
    backdrop_path: "/v2LilmCylr3bL9TCZSj6syjowZh.jpg",
    genre_ids: [35, 18],
    id: 937278,
    original_title: "A Man Called Otto",
    overview:
      "When a lively young family moves in next door, grumpy widower Otto Anderson meets his match in a quick-witted, pregnant woman named Marisol, leading to an unlikely friendship that turns his world upside down.",
    poster_path: "/130H1gap9lFfiTF9iDrqNIkFvC9.jpg",
    release_date: "2022-12-28",
    title: "A Man Called Otto",
    vote_average: 7.9,
  },
  {
    backdrop_path: "/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg",
    genre_ids: [18, 28],
    id: 677179,
    original_title: "Creed III",
    overview:
      "After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damien Anderson, resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damien - a fighter who has nothing to lose.",
    poster_path: "/vJU3rXSP9hwUuLeq8IpfsJShLOk.jpg",
    release_date: "2023-03-01",
    title: "Creed III",
    vote_average: 7,
  },
  {
    backdrop_path: "/9Rq14Eyrf7Tu1xk0Pl7VcNbNh1n.jpg",
    genre_ids: [28, 12, 53],
    id: 646389,
    original_title: "Plane",
    overview:
      "After a heroic job of successfully landing his storm-damaged aircraft in a war zone, a fearless pilot finds himself between the agendas of multiple militias planning to take the plane and its passengers hostage.",
    poster_path: "/qi9r5xBgcc9KTxlOLjssEbDgO0J.jpg",
    release_date: "2023-01-12",
    title: "Plane",
    vote_average: 6.9,
  },
  {
    backdrop_path: "/32GH8Mi4GmTPIQyd6IW1FFrHWrj.jpg",
    genre_ids: [28],
    id: 965839,
    original_title: "Lord of the Streets",
    overview:
      "When Jason Dyson refuses to make his prized fighter throw an MMA match, a notorious gangster collects his debt by killing the fighter and kidnapping Jason's daughter. Now he must train a prisoner to endure five consecutive underground fights to save her.",
    poster_path: "/n9YWVQRc0zw0nwrFcOkOpffZxjc.jpg",
    release_date: "2022-04-22",
    title: "Lord of the Streets",
    vote_average: 4.9,
  },
  {
    backdrop_path: "/ovM06PdF3M8wvKb06i4sjW3xoww.jpg",
    genre_ids: [878, 12, 28],
    id: 76600,
    original_title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    release_date: "2022-12-14",
    title: "Avatar: The Way of Water",
    vote_average: 7.7,
  },
  {
    backdrop_path: "/dlrWhn0G3AtxYUx2D9P2bmzcsvF.jpg",
    genre_ids: [878, 27, 35],
    id: 536554,
    original_title: "M3GAN",
    overview:
      "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
    poster_path: "/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg",
    release_date: "2022-12-28",
    title: "M3GAN",
    vote_average: 7.5,
  },
  {
    backdrop_path: "/k4V6EvpcOsu8CX10JD0H53lFXLq.jpg",
    genre_ids: [53, 28, 18, 80],
    id: 1058949,
    original_title: "Little Dixie",
    overview:
      "Erstwhile Special Forces operative Doc Alexander is asked to broker a truce with the Mexican drug cartel in secrecy. When Oklahoma Governor Richard Jeffs celebrates the execution of a high-ranking cartel member on TV, his Chief of Staff and Doc inform him about the peace he just ended. But it’s too late, as Cuco, the cartel’s hatchet man, has set his vengeful sights on Doc’s daughter Dixie.",
    poster_path: "/cmWTZj9zzT9KFt3XyL0gssL7Ig8.jpg",
    release_date: "2023-02-03",
    title: "Little Dixie",
    vote_average: 5.9,
  },
  {
    backdrop_path: "/xnAi4BRoO3ZQ3wwxGn6UNoxQzDq.jpg",
    genre_ids: [80, 28],
    id: 823999,
    
    original_title: "Diabolik - Ginko all'attacco!",
    overview:
      "Diabolik nearly gets caught in Inspector Ginko's latest trap, leaving his partner in crime Eva Kant behind in the escape. Furious, Eva offers Ginko her help in capturing the King of Terror, but the former has to face the return of an old flame of his: Altea, Duchess of Vallenberg.",
    poster_path: "/8QVbWBv94BAT9u1q9uJccwOxMzt.jpg",
    release_date: "2022-11-17",
    title: "Diabolik - Ginko Attacks",
    vote_average: 5.5,
  },
  {
    backdrop_path: "/A2avUoNFstnBhAnHiogXQs4c9Bt.jpg",
    genre_ids: [18, 27, 9648],
    id: 772515,
    original_title: "Huesera",
    overview:
      "Valeria's joy at becoming a first-time mother is quickly taken away when she's cursed by a sinister entity. As danger closes in, she's forced deeper into a chilling world of dark magic that threatens to consume her.",
    poster_path: "/1mZcxuL4GLUvPdEXC4iZPjG2EO3.jpg",
    release_date: "2023-02-10",
    title: "Huesera: The Bone Woman",
    vote_average: 6,
  },
  {
    backdrop_path: "/af1tFYzzT2mHIy2l7nTIU8PWfak.jpg",
    genre_ids: [80, 18, 53],
    id: 842942,
    original_title: "Bandit",
    overview:
      "After escaping a Michigan prison, a charming career criminal assumes a new identity in Canada and goes on to rob a record 59 banks and jewellery stores while being hunted by a rogue task force. Based on the story of The Flying Bandit.",
    poster_path: "/yph9PAbmjYPvyvbeZvdYIhCZHEu.jpg",
    release_date: "2022-09-23",
    title: "Bandit",
    vote_average: 6.1,
  },
  {
    backdrop_path: "/9Cg3XKMDNg7jAMwiVcLjvdZy92X.jpg",
    genre_ids: [9648, 53, 27],
    id: 782936,
    original_title: "Nocebo",
    overview:
      "A fashion designer hires a nanny from the Philippines to assist her in caring for her family while she is suffering from what she believes is a tick-related illness. The nanny uses traditional Filipino folk healing techniques to help her, but in the process of doing so, she uncovers a horrifying truth about why she is there and why her employer is actually sick.",
    poster_path: "/3FPnDTlX0LsaU4VD5mc82BMbchA.jpg",
    release_date: "2022-11-03",
    title: "Nocebo",
    vote_average: 6.5,
  },
  {
    backdrop_path: "/zGoZB4CboMzY1z4G3nU6BWnMDB2.jpg",
    genre_ids: [28, 10749, 35],
    id: 758009,
    original_title: "Shotgun Wedding",
    overview:
      "Darcy and Tom gather their families for the ultimate destination wedding but when the entire party is taken hostage, “’Til Death Do Us Part” takes on a whole new meaning in this hilarious, adrenaline-fueled adventure as Darcy and Tom must save their loved ones—if they don’t kill each other first.",
    poster_path: "/t79ozwWnwekO0ADIzsFP1E5SkvR.jpg",
    release_date: "2022-12-28",
    title: "Shotgun Wedding",
    vote_average: 6.3,
  },
  {
    backdrop_path: "/3JSoB7eMbCd8sE8alxNiUtrNiTz.jpg",
    genre_ids: [12, 878, 35],
    id: 640146,
    original_title: "Ant-Man and the Wasp: Quantumania",
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    poster_path: "/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
    release_date: "2023-02-15",
    title: "Ant-Man and the Wasp: Quantumania",

    vote_average: 6.4,
  },
  {
    backdrop_path: "/ae4xZiU7IeFVrvXxm2GjdcTrBm.jpg",
    genre_ids: [27, 9648, 53],
    id: 934433,
    original_title: "Scream VI",
    overview:
      "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.",
    poster_path: "/t2NEaFrNFRCrBIyAETlz5sqq15H.jpg",
    release_date: "2023-03-08",
    title: "Scream VI",
    vote_average: 7.5,
  },
  {
    backdrop_path: "/wVxlmhk4OS2eCr0wTQcM4zJ20ml.jpg",
    genre_ids: [35, 18, 10749],
    id: 906221,
    original_title: "Magic Mike's Last Dance",
    overview:
      "Mike Lane takes to the stage again after a lengthy hiatus, following a business deal that went bust, leaving him broke and taking bartender gigs in Florida. For what he hopes will be one last hurrah, Mike heads to London with a wealthy socialite who lures him with an offer he can’t refuse… and an agenda all her own. With everything on the line, once Mike discovers what she truly has in mind, will he—and the roster of hot new dancers he’ll have to whip into shape—be able to pull it off?",
    poster_path: "/5C9rerMqV1X0jnRdbbsM1BswVI2.jpg",
    release_date: "2023-02-09",
    title: "Magic Mike's Last Dance",
    vote_average: 7.2,
  },
];

export const TOP_RATED_MOVIES = [
  {
    backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    genre_ids: [18, 80],
    id: 238,

    original_title: "The Godfather",
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    release_date: "1972-03-14",
    title: "The Godfather",

    vote_average: 8.7,
  },
  {
    backdrop_path: "/wPU78OPN4BYEgWYdXyg0phMee64.jpg",
    genre_ids: [18, 80],
    id: 278,
    original_title: "The Shawshank Redemption",
    overview:
      "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    poster_path: "/hBcY0fE9pfXzvVaY4GKarweriG2.jpg",
    release_date: "1994-09-23",
    title: "The Shawshank Redemption",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/ejniJnlOdtSgtbh8D7u2RxT6Uli.jpg",
    genre_ids: [35, 14],
    id: 772071,
    original_title: "Cuando Sea Joven",
    overview:
      '70-year-old Malena gets a second chance at life when she magically turns into her 22-year-old self. Now, posing as "Maria" to hide her true identity, she becomes the lead singer of her grandson\'s band and tries to recover her dream of singing, which she had to give up at some point.',
    poster_path: "/6gIJuFHh5Lj4dNaPG3TzIMl7L68.jpg",
    release_date: "2022-09-14",
    title: "Cuando Sea Joven",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/kGzFbGhp99zva6oZODW5atUtnqi.jpg",
    genre_ids: [18, 80],
    id: 240,
    original_title: "The Godfather Part II",
    overview:
      "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    poster_path: "/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
    release_date: "1974-12-20",
    title: "The Godfather Part II",
    vote_average: 8.6,
  },
  {
    backdrop_path: "/wxaBkuqVIgImjRHEMJoxL9Lq6i8.jpg",
    genre_ids: [16, 10751, 12, 14],
    id: 995133,
    original_title: "The Boy, the Mole, the Fox and the Horse",
    overview:
      "The unlikely friendship of a boy, a mole, a fox and a horse traveling together in the boy’s search for home.",
    poster_path: "/oQRgyQCzcyZvE6w5heM9ktVY0LT.jpg",
    release_date: "2022-12-25",
    title: "The Boy, the Mole, the Fox and the Horse",
    vote_average: 8.6,
  },
  {
    backdrop_path: "/zb6fM1CX41D9rF9hdgclu0peUmy.jpg",
    genre_ids: [18, 36, 10752],
    id: 424,
    original_title: "Schindler's List",
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    poster_path: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-12-15",
    title: "Schindler's List",
    vote_average: 8.6,
  },
  {
    backdrop_path: "/vI3aUGTuRRdM7J78KIdW98LdxE5.jpg",
    genre_ids: [35, 18, 10749],
    id: 19404,
    original_title: "दिलवाले दुल्हनिया ले जायेंगे",
    overview:
      "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    poster_path: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
    release_date: "1995-10-19",
    title: "Dilwale Dulhania Le Jayenge",
    vote_average: 8.6,
  },
  {
    backdrop_path: "/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
    genre_ids: [16, 10751, 14],
    id: 129,
    original_title: "千と千尋の神隠し",
    overview:
      "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    poster_path: "/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    release_date: "2001-07-20",
    title: "Spirited Away",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/qqHQsStV6exghCM7zbObuYBiYxw.jpg",
    genre_ids: [18],
    id: 389,
    original_title: "12 Angry Men",
    overview:
      "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
    poster_path: "/ppd84D2i9W8jXmsyInGyihiSyqz.jpg",
    release_date: "1957-04-10",
    title: "12 Angry Men",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg",
    genre_ids: [10749, 16, 18],
    id: 372058,
    original_title: "君の名は。",
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    poster_path: "/q719jXXEzOoYaps6babgKnONONX.jpg",
    release_date: "2016-08-26",
    title: "Your Name.",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    genre_ids: [35, 53, 18],
    id: 496243,
    original_title: "기생충",
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    release_date: "2019-05-30",
    title: "Parasite",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/pbEkjhdfP7yuDcMB78YEZwgD4IN.jpg",
    genre_ids: [18, 28, 80, 53],
    id: 155,
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    release_date: "2008-07-14",
    title: "The Dark Knight",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/vxJ08SvwomfKbpboCWynC3uqUg4.jpg",
    genre_ids: [14, 18, 80],
    id: 497,
    original_title: "The Green Mile",
    overview:
      "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
    poster_path: "/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
    release_date: "1999-12-10",
    title: "The Green Mile",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    genre_ids: [53, 80],
    id: 680,
    original_title: "Pulp Fiction",
    overview:
      "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    release_date: "1994-09-10",
    title: "Pulp Fiction",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/eoCSp75lxatmIa6aGqfnzwtbttd.jpg",
    genre_ids: [37],
    id: 429,
    
    original_title: "Il buono, il brutto, il cattivo",
    overview:
      "While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.",
    poster_path: "/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg",
    release_date: "1966-12-23",
    title: "The Good, the Bad and the Ugly",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg",
    genre_ids: [35, 18, 10749],
    id: 13,
    original_title: "Forrest Gump",
    overview:
      "A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.",
    poster_path: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    release_date: "1994-06-23",
    title: "Forrest Gump",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/lXhgCODAbBXL5buk9yEmTpOoOgR.jpg",
    genre_ids: [12, 14, 28],
    id: 122,
    original_title: "The Lord of the Rings: The Return of the King",
    overview:
      "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
    poster_path: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    release_date: "2003-12-01",
    title: "The Lord of the Rings: The Return of the King",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg",
    genre_ids: [10749, 16],
    id: 372754,
    original_title: "同級生",
    overview:
      "Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.",
    poster_path: "/cIfRCA5wEvj9tApca4UDUagQEiM.jpg",
    release_date: "2016-02-20",
    title: "Dou kyu sei – Classmates",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/w2uGvCpMtvRqZg6waC1hvLyZoJa.jpg",
    genre_ids: [10749],
    id: 696374,
    original_title: "Gabriel's Inferno",
    overview:
      "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
    poster_path: "/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg",
    release_date: "2020-05-29",
    title: "Gabriel's Inferno",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/sw7mordbZxgITU877yTpZCud90M.jpg",
    genre_ids: [18, 80],
    id: 769,
    original_title: "GoodFellas",
    overview:
      "The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.",
    poster_path: "/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    release_date: "1990-09-12",
    title: "GoodFellas",
    vote_average: 8.5,
  },
];

export const UPCOMING_MOVIES = [
  {
    backdrop_path: "/jr8tSoJGj33XLgFBy6lmZhpGQNu.jpg",
    genre_ids: [16, 12, 35, 10751],
    id: 315162,
    original_title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    release_date: "2022-12-07",
    title: "Puss in Boots: The Last Wish",
    vote_average: 8.4,
  },
  {
    backdrop_path: "/v2LilmCylr3bL9TCZSj6syjowZh.jpg",
    genre_ids: [35, 18],
    id: 937278,
    original_title: "A Man Called Otto",
    overview:
      "When a lively young family moves in next door, grumpy widower Otto Anderson meets his match in a quick-witted, pregnant woman named Marisol, leading to an unlikely friendship that turns his world upside down.",
    poster_path: "/130H1gap9lFfiTF9iDrqNIkFvC9.jpg",
    release_date: "2022-12-28",
    title: "A Man Called Otto",
    vote_average: 7.9,
  },
  {
    backdrop_path: "/dlrWhn0G3AtxYUx2D9P2bmzcsvF.jpg",
    genre_ids: [878, 27, 35],
    id: 536554,
    original_title: "M3GAN",
    overview:
      "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
    poster_path: "/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg",
    release_date: "2022-12-28",
    title: "M3GAN",
    vote_average: 7.5,
  },
  {
    backdrop_path: "/A2avUoNFstnBhAnHiogXQs4c9Bt.jpg",
    genre_ids: [18, 27, 9648],
    id: 772515,
    overview:
      "Valeria's joy at becoming a first-time mother is quickly taken away when she's cursed by a sinister entity. As danger closes in, she's forced deeper into a chilling world of dark magic that threatens to consume her.",
    poster_path: "/1mZcxuL4GLUvPdEXC4iZPjG2EO3.jpg",
    release_date: "2023-02-10",
    title: "Huesera: The Bone Woman",
    vote_average: 6,
  },
  {
    backdrop_path: "/zGoZB4CboMzY1z4G3nU6BWnMDB2.jpg",
    genre_ids: [28, 10749, 35],
    id: 758009,
    original_title: "Shotgun Wedding",
    overview:
      "Darcy and Tom gather their families for the ultimate destination wedding but when the entire party is taken hostage, “’Til Death Do Us Part” takes on a whole new meaning in this hilarious, adrenaline-fueled adventure as Darcy and Tom must save their loved ones—if they don’t kill each other first.",
    poster_path: "/t79ozwWnwekO0ADIzsFP1E5SkvR.jpg",
    release_date: "2022-12-28",
    title: "Shotgun Wedding",
    vote_average: 6.3,
  },
  {
    backdrop_path: "/ae4xZiU7IeFVrvXxm2GjdcTrBm.jpg",
    genre_ids: [27, 9648, 53],
    id: 934433,
    original_title: "Scream VI",
    overview:
      "Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.",
    poster_path: "/t2NEaFrNFRCrBIyAETlz5sqq15H.jpg",
    release_date: "2023-03-08",
    title: "Scream VI",
    vote_average: 7.5,
  },
  {
    backdrop_path: "/jDkmlTz9xBmhsIIyORb68VqRlL2.jpg",
    genre_ids: [27],
    id: 955991,
    original_title: "The Offering",
    overview:
      "In the wake of a young Jewish girl’s disappearance, the son of a Hasidic funeral director returns home with his pregnant wife in hopes of reconciling with his father. Little do they know that directly beneath them in the family morgue, an ancient evil with sinister plans for the unborn child lurks inside a mysterious corpse.",
    poster_path: "/tbaTFgGIaTL1Uhd0SMob6Dhi5cK.jpg",
    release_date: "2022-09-23",
    title: "The Offering",
    vote_average: 5.6,
  },
  {
    backdrop_path: "/hJoe1i1MXoO7sXkbQRuONvUNPEo.jpg",
    genre_ids: [16, 12, 10751, 14],
    id: 502356,
    original_title: "The Super Mario Bros. Movie",
    overview:
      "While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.",
    poster_path: "/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg",
    release_date: "2023-03-30",
    title: "The Super Mario Bros. Movie",
    vote_average: 0,
  },
  {
    backdrop_path: "/f9PSbuMeBS5CuHEOVyymg5lcq8J.jpg",
    genre_ids: [28, 53, 9648, 80, 27],
    id: 996727,
    original_title: "The Price We Pay",
    overview:
      "After a pawn shop robbery goes askew, two criminals take refuge at a remote farmhouse to try to let the heat die down, but find something much more menacing.",
    poster_path: "/8fwJt0qZieQ7dKaiiqehObWpXYT.jpg",
    release_date: "2023-01-13",
    title: "The Price We Pay",
    vote_average: 6.1,
  },
  {
    backdrop_path: "/A5JyEZvXHbPLN2cU65oB9NaIuYH.jpg",
    genre_ids: [18, 9648, 53],
    id: 768362,
    original_title: "Missing",
    overview:
      "When her mother disappears while on vacation in Colombia with her new boyfriend, June’s search for answers is hindered by international red tape. Stuck thousands of miles away in Los Angeles, June creatively uses all the latest technology at her fingertips to try and find her before it’s too late. But as she digs deeper, her digital sleuthing raises more questions than answers... and when June unravels secrets about her mom, she discovers that she never really knew her at all.",
    poster_path: "/jYXJW19PMEUrpyavEHrnnlItQn1.jpg",
    release_date: "2023-01-19",
    title: "Missing",
    vote_average: 7.7,
  },
  {
    backdrop_path: "/6ikTLqVFjQvQUC06QBuEHGTbkWH.jpg",
    genre_ids: [53, 878, 28],
    id: 700391,
    original_title: "65",
    overview:
      "After a catastrophic crash on an unknown planet, pilot Mills quickly discovers he's actually stranded on Earth…65 million years ago. Now, with only one chance at rescue, Mills and the only other survivor, Koa, must make their way across an unknown terrain riddled with dangerous prehistoric creatures in an epic fight to survive.",
    poster_path: "/uMMIeMVk1TCG3CZilpxbzFh0JKT.jpg",
    release_date: "2023-03-02",
    title: "65",
    vote_average: 6.6,
  },
  {
    backdrop_path: "/e8BCc8Jk11dnSffI6ElICLePvLZ.jpg",
    genre_ids: [28, 53, 80],
    id: 603692,
    original_title: "John Wick: Chapter 4",
    overview:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    release_date: "2023-03-22",
    title: "John Wick: Chapter 4",
    vote_average: 0,
  },
  {
    backdrop_path: "/v2GqQcm4Yg54ADrdbEi4Y1FZZhz.jpg",
    genre_ids: [53, 27],
    id: 746524,
    original_title: "Blood",
    overview:
      "Jess, a newly separated mother and nurse, moves into her old family farmhouse with Tyler, her teenage daughter, and Owen, her eight-year-old son. One night, the family dog senses something in the woods and runs off to find it. He returns a couple of days later and attacks Owen, savagely biting him before Jess is able to intervene. Owen is rushed to the hospital. His condition worsens, and no one can figure out why... until Jess discovers a disturbing cure...",
    poster_path: "/gCUFtTvjK4gbmjVxhx8bhyOhAeW.jpg",
    release_date: "2023-01-12",
    title: "Blood",
    vote_average: 5.9,
  },
  {
    backdrop_path: "/ofteFQqIntae7wqVAYYyXOCmkF1.jpg",
    genre_ids: [27, 53],
    id: 980078,
    original_title: "Winnie-the-Pooh: Blood and Honey",
    overview:
      "Christopher Robin is headed off to college and he has abandoned his old friends, Pooh and Piglet, which then leads to the duo embracing their inner monsters.",
    poster_path: "/wtFwgFFk1ze789ghcadWGEVjj3N.jpg",
    release_date: "2023-01-27",
    title: "Winnie-the-Pooh: Blood and Honey",
    vote_average: 5.5,
  },
  {
    backdrop_path: "/vn4vwKXiqpcmThenluyWhxMvTQK.jpg",
    genre_ids: [14, 28, 35],
    id: 594767,
    original_title: "Shazam! Fury of the Gods",
    overview:
      'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
    poster_path: "/zpCCTtuQMHiHycpsrWnW2eCrBql.jpg",
    release_date: "2023-03-15",
    title: "Shazam! Fury of the Gods",
    vote_average: 0,
  },
  {
    backdrop_path: "/eIeCUHk8q7smdd2KAiPBmceN7QS.jpg",
    genre_ids: [35, 10751, 10402],
    id: 830784,
    original_title: "Lyle, Lyle, Crocodile",
    overview:
      "When the Primm family moves to New York City, their young son Josh struggles to adapt to his new school and new friends. All of that changes when he discovers Lyle — a singing crocodile who loves baths, caviar and great music — living in the attic of his new home. But when Lyle’s existence is threatened by evil neighbor Mr. Grumps, the Primms must band together to show the world that family can come from the most unexpected places.",
    poster_path: "/irIS5Tn3TXjNi1R9BpWvGAN4CZ1.jpg",
    release_date: "2022-10-07",
    title: "Lyle, Lyle, Crocodile",
    vote_average: 7.6,
  },
  {
    backdrop_path: "/jBIMZ0AlUYuFNsKbd4L6FojWMoy.jpg",
    genre_ids: [16, 35, 10749],
    id: 820067,
    original_title: "映画 五等分の花嫁",
    overview:
      "When five lovely young girls who hate studying hire part-time tutor Futaro, he guides not only their education but also their hearts. Time spent has brought them all closer, with feelings growing within the girls and Futaro. As they finish their third year of high school and their last school festival approaches, they set their sights on what’s next. Is there a future with one of them and Futaro?",
    poster_path: "/xTlAhTivEObHRFBKjAMVSyRQGv2.jpg",
    release_date: "2022-05-20",
    title: "The Quintessential Quintuplets Movie",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/uI1EvYeXNri9BbpcP3YzE4XVUJW.jpg",
    genre_ids: [12, 16, 35, 10751, 14],
    id: 816904,
    original_title: "Momias",
    overview:
      "Through a series of unfortunate events, three mummies end up in present-day London and embark on a wacky and hilarious journey in search of an old ring belonging to the Royal Family, that was stolen by the ambitious archaeologist Lord Carnaby.",
    poster_path: "/r6Ghtw9ENhTXfeUsd1Al20ZAvX.jpg",
    release_date: "2023-01-05",
    title: "Mummies",
    vote_average: 6.1,
  },
  {
    backdrop_path: "/fh7aM10THQzivGU7kAkgKrgzot4.jpg",
    genre_ids: [28, 12, 14],
    id: 493529,
    original_title: "Dungeons & Dragons: Honor Among Thieves",
    overview:
      "A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.",
    poster_path: "/6LuXaihVIoJ5FeSiFb7CZMtU7du.jpg",
    release_date: "2023-03-29",
    title: "Dungeons & Dragons: Honor Among Thieves",
    vote_average: 0,
  },
  {
    backdrop_path: "/yVpILj2KX3WylLLT49GZbj2M9AO.jpg",
    genre_ids: [10749, 18],
    id: 845659,
    original_title: "Perfect Addiction",
    overview:
      "When successful boxing trainer Sienna Lane discovers that her boyfriend Jax, the reigning champion, has been cheating on her with her own sister, she sets out to get revenge by training the one man capable of dethroning him: his arch-nemesis Kayden.",
    poster_path: "/AaLnyYIAmMpHHPzowyoaY5sO2a1.jpg",
    release_date: "2023-02-16",
    title: "Perfect Addiction",
    vote_average: 4.5,
  },
];

