export const POPULAR_TV = [
  {
    backdrop_path: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    first_air_date: "2023-01-15",
    genre_ids: [18],
    id: 100088,
    name: "The Last of Us",
    original_name: "The Last of Us",
    overview:
      "Año 2023, veinte años después del comienzo de una plaga mundial que infectó a población con un hongo mutado transformando a las personas en unas criaturas caníbales, el contrabandista Joel tiene la misión de escoltar a la adolescente Ellie por un mundo postapocalíptico en el nada va a ser fácil para los viajeros.  Joel todavía vive atormentado por el recuerdo de su única hija. Ellie es portadora de algo que podría cambiar el destino de la humanidad ¿Conseguirán sobrevivir los dos?",
    poster_path: "/tNQWO6cNzQYCyvw36mUcAQQyf5F.jpg",
    vote_average: 8.8,
  },
  {
    backdrop_path: "/epXXeg1AAfCRw6b76Lx1YQj8VzK.jpg",
    first_air_date: "2023-02-16",
    genre_ids: [],
    id: 196157,
    name: "星落凝成糖",
    original_name: "星落凝成糖",
    overview: "",
    poster_path: "/3nFfGy8uWRX0DquD9o6dYcbVrao.jpg",
    vote_average: 3,
  },
  {
    backdrop_path: "/3FLHePl9Y3n4BidLVjIA9qSRDOE.jpg",
    first_air_date: "2021-08-03",
    genre_ids: [10766],
    id: 130542,
    name: "Bhagya Lakshmi",
    original_name: "Bhagya Lakshmi",
    overview: "",
    poster_path: "/7wuKrFvbX7kAIF0ctotARsqayPo.jpg",
    vote_average: 5.2,
  },
  {
    backdrop_path: "/xgZ9AhvXqi9aSDWzCpoC9JAkLPY.jpg",
    first_air_date: "2019-01-01",
    genre_ids: [35],
    id: 85425,
    name: "Drága örökösök",
    original_name: "Drága örökösök",
    overview: "",
    poster_path: "/r6B4o4Bgg7cQmt8XDsGsyYaLHmP.jpg",
    vote_average: 5.3,
  },
  {
    backdrop_path: "/t2rAdgjSh0WYbXzdOB5zTDqzdCI.jpg",
    first_air_date: "2022-11-02",
    genre_ids: [18],
    id: 213713,
    name: "फालतू",
    original_name: "फालतू",
    overview: "",
    poster_path: "/lgyFuoXs7GvKJN0mNm7z7OMOFuZ.jpg",
    vote_average: 5,
  },
  {
    backdrop_path: "/3n2TjKw3HrwDqgVgcynvantOfS3.jpg",
    first_air_date: "2023-01-04",
    genre_ids: [18, 10751],
    id: 215103,
    name: "तेरी मेरी डोरियाँ",
    original_name: "तेरी मेरी डोरियाँ",
    overview: "",
    poster_path: "/4BHDmYiuSnNL3nqKIOzLJKYX4AN.jpg",
    vote_average: 6,
  },
  {
    backdrop_path: null,
    first_air_date: "2021-10-27",
    genre_ids: [18],
    id: 197109,
    name: "ये रिश्ता क्या कहलाता है",
    original_name: "ये रिश्ता क्या कहलाता है",
    overview: "",
    poster_path: "/6ZfiG4P7jivJV0wgcNMSiS2Owhh.jpg",
    vote_average: 4.9,
  },
  {
    backdrop_path: "/o8zk3QmHYMSC7UiJgFk81OFF1sc.jpg",
    first_air_date: "2022-08-22",
    genre_ids: [10766, 18],
    id: 204095,
    name: "Mar do Sertão",
    original_name: "Mar do Sertão",
    overview: "",
    poster_path: "/ixgnqO8xhFMb1zr8RRFsyeZ9CdD.jpg",
  },
  {
    backdrop_path: "/6Lw54zxm6BAEKJeGlabyzzR5Juu.jpg",
    first_air_date: "2019-11-12",
    genre_ids: [10765, 10759, 18],
    id: 82856,
    name: "The Mandalorian",
    original_name: "The Mandalorian",
    overview:
      "En el anárquico período tras el hundimiento del Imperio Galáctico, un cazarrecompensas con armadura conocido solo como El Mandaloriano emprende una misión bien remunerada aunque enigmática.",
    poster_path: "/mzzZKJ4fvwib8Fty1tv4Vtp9R0b.jpg",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/luUTaPpTBM8BjP4wgCLxNIPkx6k.jpg",
    first_air_date: "1988-06-01",
    genre_ids: [10759, 18],
    id: 19530,
    name: "霹雳布袋戏",
    original_name: "霹雳布袋戏",
    overview: "",
    poster_path: "/c6CKmPSXO8omy0eHQX7TcEtz72i.jpg",
    vote_average: 7.4,
  },
  {
    backdrop_path: "/qcpC9lv6VLL4Zw45EveYELyje1w.jpg",
    first_air_date: "2020-10-05",
    genre_ids: [18, 10766, 10751],
    id: 111453,
    name: "घुम है किसिकी प्यार में",
    original_name: "घुम है किसिकी प्यार में",
    overview: "",
    poster_path: "/uNjnoT3RChs2r7O9pDyx7TNBvIj.jpg",
    vote_average: 5.8,
  },
  {
    backdrop_path: "/ymkFaEO0UdYXKIgcWZ23TlYIRD9.jpg",
    first_air_date: "2020-11-16",
    genre_ids: [18, 10766, 10751],
    id: 113218,
    name: "Imlie",
    original_name: "इमली",
    overview:
      "Todo lo que Imlie quería era crearse un nombre en la ciudad. Pero a su llegada, se encuentra atrapada en medio de la historia de amor de Aditya y Malini.",
    poster_path: "/brajFHvqeitbp7ifevWpFpirS4S.jpg",
    vote_average: 5.6,
  },
  {
    backdrop_path: "/mAJ84W6I8I272Da87qplS2Dp9ST.jpg",
    first_air_date: "2023-01-23",
    genre_ids: [9648, 18],
    id: 202250,
    name: "Dirty Linen",
    original_name: "Dirty Linen",
    overview: "",
    poster_path: "/ujlkQtHAVShWyWTloGU2Vh5Jbo9.jpg",
    vote_average: 4.9,
  },
  {
    backdrop_path: "/gQxaF79LUTtopdYHsuS8lUr9rvF.jpg",
    first_air_date: "2021-11-14",
    genre_ids: [18, 80],
    id: 97951,
    name: "Mayor of Kingstown",
    original_name: "Mayor of Kingstown",
    overview:
      "Ambientada en una pequeña ciudad de Michigan donde la única industria que queda son las cárceles federales, estatales y privadas, la historia sigue a la familia McClusky, los intermediarios del poder entre la policía, los delincuentes, los presos, los guardias de prisiones y los políticos, en una ciudad completamente dependiente de las prisiones.  y los prisioneros que contienen.",
    poster_path: "/s18V51BeLOr9vB0rXm3QcVS6wwL.jpg",
    vote_average: 8.2,
  },
  {
    backdrop_path: "/26be9JndZG6uYBfNPAy51dUKj0y.jpg",
    first_air_date: "2022-01-03",
    genre_ids: [10766],
    id: 154571,
    name: "Quero é Viver",
    original_name: "Quero é Viver",
    overview: "",
    poster_path: "/bAp4W1ppwVlp7EpJb91RwTTLhm3.jpg",
    vote_average: 6.4,
  },
  {
    backdrop_path: "/1vgdmeW6keP47DQ1tGwfVCdUKqu.jpg",
    first_air_date: "2020-10-12",
    genre_ids: [35],
    id: 111551,
    name: "Χαιρέτα μου τον Πλάτανο",
    original_name: "Χαιρέτα μου τον Πλάτανο",
    overview: "",
    poster_path: "/vAu6or1W4G1q7wJxQfDmATtnIg.jpg",
    vote_average: 5.5,
  },
  {
    backdrop_path: null,
    first_air_date: "",
    genre_ids: [35],
    id: 213017,
    name: "Lo Zoo di 105",
    original_name: "Lo Zoo di 105",
    overview: "",
    poster_path: "/6KL71OV5wHQGk5KZMP3qp7Mj5HA.jpg",
    vote_average: 3.7,
  },
  {
    backdrop_path: "/caGVr9Il2gj8bN4ow6qsLm60TxM.jpg",
    first_air_date: "2005-03-27",
    genre_ids: [18],
    id: 1416,
    name: "Anatomía de Grey",
    original_name: "Grey's Anatomy",
    overview:
      "La vida de Meredith Grey no es nada fácil. Intenta tomar las riendas de su vida, aunque su trabajo sea de esos que te hacen la vida imposible. Meredith es una cirujana interna de primer año en el Hospital Grace de Seattle, el programa de prácticas más duro de la Facultad de Medicina de Harvard. Y ella lo va a comprobar. Pero no estará sola. Un elenco de compañeros de promoción tendrán que superar la misma prueba. Ahora están en el mundo real, son doctores del hospital. Y en un mundo donde la experiencia en el trabajo puede ser un factor de vida o muerte, todos ellos tendrán que lidiar con los altibajos de sus vidas personales.",
    poster_path: "/jPzW61WlkyHVdvm8dCQZveTvmgW.jpg",
    vote_average: 8.3,
  },
  {
    backdrop_path: "/tLL91JBiCCvBF7oKSN6dFR7yd8c.jpg",
    first_air_date: "2021-12-20",
    genre_ids: [10764],
    id: 153870,
    name: "Shark Tank India",
    original_name: "Shark Tank India",
    overview: "",
    poster_path: "/iGw6R4e4G07xjffVifFLSN3dEAb.jpg",
    vote_average: 7.4,
  },
  {
    backdrop_path: "/znjIKAlfJTkcWw6pcD6Bxm4L3dq.jpg",
    first_air_date: "2023-01-16",
    genre_ids: [18],
    id: 215546,
    name: "Luv Is",
    original_name: "Luv Is",
    overview: "",
    poster_path: "/nwKL1HEx6IwK2cMzXFM9c0V1F3y.jpg",
    vote_average: 7,
  },
];

export const TOP_RATED_TV = [
  {
    backdrop_path: "/99vBORZixICa32Pwdwj0lWcr8K.jpg",
    first_air_date: "2021-09-03",
    genre_ids: [10764],
    id: 130392,
    name: "The D'Amelio Show",
    original_name: "The D'Amelio Show",
    overview:
      "Al pasar de una relativa sombra y una vida aparentemente normal a ser lanzados a los focos de Hollywood casi de la noche a la mañana, los D’Amelio se enfrentan a retos y oportunidades que nunca habrían imaginado. Charli, Dixie, Heidi y Marc hacen todo lo posible por mantenerse unidos mientras intentan adaptarse a la vida en Hollywood.",
    poster_path: "/phv2Jc4H8cvRzvTKb9X1uKMboTu.jpg",
    vote_average: 8.9,
  },
  {
    backdrop_path: "/hwIAR9FDsKULo8efoOUuxsFtO2u.jpg",
    first_air_date: "2008-01-20",
    genre_ids: [18],
    id: 1396,
    name: "Breaking Bad",
    original_name: "Breaking Bad",
    overview:
      "Tras cumplir 50 años, Walter White (Bryan Cranston), un profesor de química de un instituto de Albuquerque, Nuevo México, se entera de que tiene un cáncer de pulmón incurable. Casado con Skyler (Anna Gunn) y con un hijo discapacitado (RJ Mitte), la brutal noticia lo impulsa a dar un drástico cambio a su vida: decide, con la ayuda de un antiguo alumno (Aaron Paul), fabricar anfetaminas y ponerlas a la venta. Lo que pretende es liberar a su familia de problemas económicos cuando se produzca el fatal desenlace.",
    poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    vote_average: 8.9,
  },
  {
    backdrop_path: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    first_air_date: "2023-01-15",
    genre_ids: [18],
    id: 100088,
    name: "The Last of Us",
    original_name: "The Last of Us",
    overview:
      "Año 2023, veinte años después del comienzo de una plaga mundial que infectó a población con un hongo mutado transformando a las personas en unas criaturas caníbales, el contrabandista Joel tiene la misión de escoltar a la adolescente Ellie por un mundo postapocalíptico en el nada va a ser fácil para los viajeros.  Joel todavía vive atormentado por el recuerdo de su única hija. Ellie es portadora de algo que podría cambiar el destino de la humanidad ¿Conseguirán sobrevivir los dos?",
    poster_path: "/tNQWO6cNzQYCyvw36mUcAQQyf5F.jpg",
    vote_average: 8.8,
  },
  {
    backdrop_path: "/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg",
    first_air_date: "2021-11-06",
    genre_ids: [16, 10765, 10759, 18],
    id: 94605,
    name: "Arcane",
    original_name: "Arcane",
    overview:
      "Con las dispares ciudades de Piltover y Zaun como telón de fondo, dos hermanas luchan en bandos opuestos de una guerra entre tecnologías mágicas y creencias enfrentadas.",
    poster_path: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/uGy4DCmM33I7l86W7iCskNkvmLD.jpg",
    first_air_date: "2013-12-02",
    genre_ids: [16, 35, 10765, 10759],
    id: 60625,
    name: "Rick y Morty",
    original_name: "Rick and Morty",
    overview:
      "Comedia animada que narra las aventuras de un científico loco Rick Sánchez, que regresa después de 20 años para vivir con su hija, su marido y sus hijos Morty y Summer.",
    poster_path: "/5Yiep9EwcQgLolg013ETBVqHxuD.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/70YdbMELM4b8x8VXjlubymb2bQ0.jpg",
    first_air_date: "2017-03-19",
    genre_ids: [18, 10751],
    id: 70785,
    name: "Anne with an E",
    original_name: "Anne with an E",
    overview:
      "Anne Shirley es una niña huérfana que vive en un pequeño pueblo llamado Avonlea que pertenece a la Isla del Príncipe Eduardo, en el año 1890. Después de una infancia difícil, donde fue pasando de orfanato a hogares de acogida, es enviada por error a vivir con una solterona y su hermano. Cuando cumple 13 años, Anne va a conseguir transformar su vida y el pequeño pueblo donde vive gracias a su fuerte personalidad, intelecto e imaginación.",
    poster_path: "/6P6tXhjT5tK3qOXzxF9OMLlG7iz.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/4Mt7WHox67uJ1yErwTBFcV8KWgG.jpg",
    first_air_date: "1999-10-20",
    genre_ids: [10759, 35, 16],
    id: 37854,
    name: "One Piece",
    original_name: "ワンピース",
    overview:
      'Riqueza, fama, poder... un hombre había obtenido todo en este mundo, era el Rey de los Piratas Gold Roger. Antes de morir sus últimas palabras inspiraron al mundo a aventurarse al mar: "¿Mi tesoro? Si lo queréis es vuestro... lo he escondido todo en ese lugar". Y así dio comienzo lo que se conoce como la Gran Era de la Piratería, lanzando a cientos de piratas al mar para encontrar el gran tesoro One Piece. Esta serie relata las aventuras y desventuras de uno de esos piratas, Monkey D. Luffy, quien accidentalmente de pequeño, comió una Fruta del Diablo (Akuma no Mi en japonés), en particular una Gomu Gomu no Mi que hizo que su cuerpo ganara las propiedades físicas de la goma, convirtiéndose en el hombre de goma. Luffy, después de dicho suceso, decide que se convertirá en el próximo Rey de los Piratas y para ello, deberá encontrar el "One Piece".',
    poster_path: "/oag7edI9flSMawmNySEiSEJAbrf.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/5DUMPBSnHOZsbBv81GFXZXvDpo6.jpg",
    first_air_date: "2022-10-12",
    genre_ids: [16, 10759, 10765, 35],
    id: 114410,
    name: "Chainsaw Man",
    original_name: "チェンソーマン",
    overview:
      'Denji es un adolescente que vive con un demonio motosierra llamado Pochita. Para pagar la deuda que le dejó su padre tras su muerte, ha tenido que ganarse el pan como puede matando demonios y vendiendo sus cadáverse a la mafia, aunque su vida siempre ha sido miserable.\n\nCuando una traición provoca la muerte de Denji, Pochita hace un contrato con él y Denji revive como "Chainsaw Man", un ser humano con el corazón de un demonio.',
    poster_path: "/oeNps5WE8umMVcNISI8M2NHk7jg.jpg",
    vote_count: 918,
  },
  {
    backdrop_path: "/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg",
    first_air_date: "2009-04-05",
    genre_ids: [10759, 16, 10765],
    id: 31911,
    name: "Fullmetal Alchemist: Brotherhood",
    original_name: "鋼の錬金術師 FULLMETAL ALCHEMIST",
    overview:
      "Remake de Fullmetal Alchemist. Edward y Alphonse rompieron la regla basica de la alquimia, la cual les trajo graves consecuencias. Para remediar esto, se embarcan en busca de alguna forma de solucionar sus males",
    poster_path: "/726CoIcNtWJJuxSyuRLjZkJwGrT.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg",
    first_air_date: "2021-03-25",
    genre_ids: [16, 10765, 10759, 18],
    id: 95557,
    name: "Invencible",
    original_name: "Invincible",
    overview:
      "Mark Grayson es un adolescente normal, excepto por el hecho de que su padre es el superhéroe más poderoso del planeta. Poco después de su decimoséptimo cumpleaños, Mark comienza a desarrollar sus propios poderes y entra en la tutela de su padre.",
    poster_path: "/mWhZ6RSyb4y0extxHl8YGoB0r3t.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/smSbK5cd8T9XHcxEUcems23BDEF.jpg",
    first_air_date: "2016-12-02",
    genre_ids: [18, 10765, 35],
    id: 67915,
    name: "GOBLIN: El solitario ser inmortal",
    original_name: "쓸쓸하고 찬란하神-도깨비",
    overview:
      "Un ser inmortal desea terminar su existencia buscando en todo el mundo su novia que es la destinada a sacar la espada que le atraviesa el pecho y solo ella es capaz de verla, pero luego de conocerse se enamoran y  es cuando todo cambia para el ser inmortal ya que debido al amor que siente encuentra una nueva razón para mantenerse vivo pero con esto pone en peligro a su amada que además es capaz de ver fantasmas, paralelamente existe un ángel de la muerte que se enamora perdidamente de la que resulta ser la reencarnación de la hermana del ser inmortal. Durante el desarrollo de esta serie se pueden disfrutar de momentos que evocan emisiones inimaginable y definitivamente no tiene ni un solo instante desperdiciado.",
    poster_path: "/qZMEiTsNlCQV27hHQE27ZtlPWyv.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/3ILMlmC30QUnYkY3XEBOyJ82Dqu.jpg",
    first_air_date: "2016-04-03",
    genre_ids: [10759, 16],
    id: 65930,
    name: "My Hero Academia",
    original_name: "僕のヒーローアカデミア",
    overview:
      "Las personas no nacen igual. El protagonista de esta historia es uno de esos casos raros que nacen sin superpoderes, pero esto no le impedirá perseguir su sueño: ser un gran héroe como el legendario All-Might. Para convertirse en el héroe que quiere ser, se apuntará a una de las academias de héroes más prestigiosas del país: Yueiko. Con la ayuda de su ídolo, All-Might, ¿podrá convertirse en un verdadero héroe?",
    poster_path: "/dmUuNVWAJumRkDNuauFaLSvga00.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/dJ8yrSokdTMnhKJw06MllSfCegb.jpg",
    first_air_date: "2019-01-12",
    genre_ids: [16, 35, 18],
    id: 83121,
    name: "Kaguya-sama: Love Is War",
    original_name: "かぐや様は告らせたい～天才たちの恋愛頭脳戦～",
    overview:
      "¡Todo vale en el amor y en la guerra! Dos genios. Dos cerebros. Dos corazones. Una batalla. ¡¿Quién declarará primero su amor?! Kaguya Shinomiya y Miyuki Shirogane son dos prodigios de gran inteligencia y quienes controlan el consejo de estudiantes de su prestigiosa academia, lo que las convierte en la crème de la crème de la élite. Pero claro, estar en la cima es algo que incluye una buena dosis de soledad como extra, y ambos acaban enamorándose el uno del otro. ¿El problema? Que ambos son demasiado orgullosos como para admitir que están enamorados, así que el primero que lo admita, ¡será el perdedor! Comienza su batalla diaria para intentar forzar al otro a declararse primero.",
    poster_path: "/xxdu5VfiQLN4ZhA4VMw3tJ1Pi6T.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/iBAtBLqCMON3NPIjyQ1wdMbpTAk.jpg",
    first_air_date: "2019-04-06",
    genre_ids: [16, 10765, 10759],
    id: 85937,
    name: "Guardianes de la Noche: Kimetsu no Yaiba",
    original_name: "鬼滅の刃",
    overview:
      "El joven Tanjiro Kamado vive felizcon su madre y hermanos pequeños en la montaña, subsistiendo humildemente gracias a la venta de carbón. Una fría mañana, después de regresar de trabajar, se encuentraa toda su familia asesinada con la excepción de su hermana Nezuko, convertida en demonio",
    poster_path: "/tK4GsDa6BREEh6Hfng1tWPuq8oE.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/2vbE9ajftJ7dkqUAyxDS0WFILx8.jpg",
    first_air_date: "2010-09-06",
    genre_ids: [16, 35],
    id: 31132,
    name: "Historias Corrientes",
    original_name: "Regular Show",
    overview:
      "Mordecai y Rigby son dos amigos inseparables que convierten en fantasía los problemas y tareas cotidianas de sus aburridos trabajos.",
    poster_path: "/6xea7V4d2xayrlBKOtMZ4wlV6wZ.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/nLKYAJCEi6OQVji1HJIxSQ74H9s.jpg",
    first_air_date: "2005-02-21",
    genre_ids: [16, 10759, 10765],
    id: 246,
    name: "Avatar: La leyenda de Aang",
    original_name: "Avatar: The Last Airbender",
    overview:
      "La historia transcurre en un mundo de gente principalmente asiática (el estilo de vida en la serie se basa en la primera mitad del siglo XIX), donde predominan las artes marciales y la manipulación de los elementos en combinación con el misticismo oriental, dando seguimiento a las aventuras de Aang, el más reciente sucesor de una larga línea de avatares, y sus amigos en un intento por salvar su místico mundo de la despiadada Nación del Fuego que busca conquistar a las demás naciones. Durante sus travesías son acechados insistentemente por el desterrado príncipe del fuego Zuko, cuyo objetivo es capturar al avatar para recuperar su honor. Esta serie es presentada como si se tratara de una serie de libros, en donde cada episodio actúa como un «capítulo», y cada temporada como un solo «libro», los cuales se titulan por el elemento temático de la temporada.",
    poster_path: "/ucNtkZfpZ6KgxqPo039nN4LAyFR.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/cHyY5z4txdVyGtYMvBJhCqCcJso.jpg",
    first_air_date: "2020-01-10",
    genre_ids: [16, 10765, 10751, 10759, 35],
    id: 92685,
    name: "Casa Búho",
    original_name: "The Owl House",
    overview:
      "Luz, una adolescente humana muy segura de sí misma, tropieza por casualidad con un portal a un nuevo mundo mágico donde se hace amiga de una bruja rebelde, Eda, y de un adorable y diminuto guerrero, King. A pesar de no tener habilidades mágicas, Luz persigue su sueño de convertirse en bruja trabajando de aprendiz para Eda en la Casa Búho y finalmente encuentra una nueva familia en un entorno poco probable.",
    poster_path: "/lE5OYF0axjCVtrxLMetA8i8QpZ8.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/790rH1ByeDJg6VPwBFxdzxHRepI.jpg",
    first_air_date: "2019-04-06",
    genre_ids: [16, 35],
    id: 85990,
    name: "Hitori Bocchi no Marumaru Seikatsu",
    original_name: "ひとりぼっちの○○生活",
    overview:
      "Hitori Bocchi sufre de extrema ansiedad social, no es buena para hablar con la gente, toma acciones muy extremas, es sorprendentemente experta en evitar a las personas, sus piernas se aprietan cuando se esfuerza demasiado, se llena de sí misma cuando está sola, vomita cuando se la expone a una tensión extrema Y a menudo se le ocurren planes. Ahora ella está ingresando a la escuela secundaria y su única amiga, Yawara Kai, asiste a una escuela diferente. Esto deja a Bocchi solo, rodeado de nuevos compañeros de clase con los que debe hacer amigos antes de que Kai vuelva a hablar con ella.",
    poster_path: "/a6OSFlD3xvVVIgbx867egPlOPpZ.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/tKh3pc5MEjCIGV7hSJX76qi8aGA.jpg",
    first_air_date: "2018-01-13",
    genre_ids: [16],
    id: 76121,
    name: "Darling in the FranXX",
    original_name: "ダーリン・イン・ザ・フランキス",
    overview:
      "En un futuro lejano, cuando la Tierra está en ruinas y la humanidad ha establecido una ciudad-fortaleza móvil bautizada como “Plantación”, unos pilotos viven en Mistilteinn, la “Jaula de pájaros”. Los niños viven allí sin conocer el mundo exterior ni la libertad. Su vida consiste en luchar y superar misiones contra unas formas de vida gigantes y misteriosas conocidas como Kyouryuu. Para enfrentarse a ellos, utilizan los robots Franxx. Un chico llamado Hiro está bautizado como Code:016 y, una vez, fue considerado un prodigio. No obstante, se ha quedado atrás y su existencia parece innecesaria. No pilotar un Franxx es igual a no existir. Un día, una chica misteriosa conocida como “Zero Two” aparece ante él y dos cuernos surgen de su cabeza.",
    poster_path: "/xjiOAYYmSf04Tq1Qa09ayWeWjU6.jpg",
    vote_average: 8.7,
  },
  {
    backdrop_path: "/fCz519JJeXEtMfR4CmM9tR7rZOB.jpg",
    first_air_date: "2022-04-14",
    genre_ids: [10764],
    id: 154521,
    name: "Las Kardashian",
    original_name: "The Kardashians",
    overview:
      "La familia a la que tanto conoces y adoras vuelve con una nueva serie dando acceso pleno a toda su vida. Kris, Kourtney, Kim, Khloé, Kendall y Kylie se exponen ante las cámaras para revelar los secretos que hay tras los titulares.",
    poster_path: "/ftbs56alkPVhyqIn68jaUrRyNTU.jpg",
    vote_average: 8.7,
  },
];

export const ON_AIR_TV = [
  {
    backdrop_path: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    first_air_date: "2023-01-15",
    genre_ids: [18],
    id: 100088,
    name: "The Last of Us",
    original_name: "The Last of Us",
    overview:
      "Año 2023, veinte años después del comienzo de una plaga mundial que infectó a población con un hongo mutado transformando a las personas en unas criaturas caníbales, el contrabandista Joel tiene la misión de escoltar a la adolescente Ellie por un mundo postapocalíptico en el nada va a ser fácil para los viajeros.  Joel todavía vive atormentado por el recuerdo de su única hija. Ellie es portadora de algo que podría cambiar el destino de la humanidad ¿Conseguirán sobrevivir los dos?",
    poster_path: "/tNQWO6cNzQYCyvw36mUcAQQyf5F.jpg",
    vote_average: 8.8,
  },
  {
    backdrop_path: "/epXXeg1AAfCRw6b76Lx1YQj8VzK.jpg",
    first_air_date: "2023-02-16",
    genre_ids: [],
    id: 196157,
    name: "星落凝成糖",
    original_name: "星落凝成糖",
    overview: "",
    poster_path: "/3nFfGy8uWRX0DquD9o6dYcbVrao.jpg",
    vote_average: 3,
  },
  {
    backdrop_path: "/3FLHePl9Y3n4BidLVjIA9qSRDOE.jpg",
    first_air_date: "2021-08-03",
    genre_ids: [10766],
    id: 130542,
    name: "Bhagya Lakshmi",
    original_name: "Bhagya Lakshmi",
    overview: "",
    poster_path: "/7wuKrFvbX7kAIF0ctotARsqayPo.jpg",
    vote_average: 5.2,
  },
  {
    backdrop_path: "/xgZ9AhvXqi9aSDWzCpoC9JAkLPY.jpg",
    first_air_date: "2019-01-01",
    genre_ids: [35],
    id: 85425,
    name: "Drága örökösök",
    original_name: "Drága örökösök",
    overview: "",
    poster_path: "/r6B4o4Bgg7cQmt8XDsGsyYaLHmP.jpg",
    vote_average: 5.3,
  },
  {
    backdrop_path: "/t2rAdgjSh0WYbXzdOB5zTDqzdCI.jpg",
    first_air_date: "2022-11-02",
    genre_ids: [18],
    id: 213713,
    name: "फालतू",
    original_name: "फालतू",
    overview: "",
    poster_path: "/lgyFuoXs7GvKJN0mNm7z7OMOFuZ.jpg",
    vote_average: 5,
  },
  {
    backdrop_path: "/3n2TjKw3HrwDqgVgcynvantOfS3.jpg",
    first_air_date: "2023-01-04",
    genre_ids: [18, 10751],
    id: 215103,
    name: "तेरी मेरी डोरियाँ",
    original_name: "तेरी मेरी डोरियाँ",
    overview: "",
    poster_path: "/4BHDmYiuSnNL3nqKIOzLJKYX4AN.jpg",
    vote_average: 6,
  },
  {
    backdrop_path: null,
    first_air_date: "2021-10-27",
    genre_ids: [18],
    id: 197109,
    name: "ये रिश्ता क्या कहलाता है",
    original_name: "ये रिश्ता क्या कहलाता है",
    overview: "",
    poster_path: "/6ZfiG4P7jivJV0wgcNMSiS2Owhh.jpg",
    vote_average: 4.9,
  },
  {
    backdrop_path: "/o8zk3QmHYMSC7UiJgFk81OFF1sc.jpg",
    first_air_date: "2022-08-22",
    genre_ids: [10766, 18],
    id: 204095,
    name: "Mar do Sertão",
    original_name: "Mar do Sertão",
    overview: "",
    poster_path: "/ixgnqO8xhFMb1zr8RRFsyeZ9CdD.jpg",
    vote_average: 4.6,
  },
  {
    backdrop_path: "/6Lw54zxm6BAEKJeGlabyzzR5Juu.jpg",
    first_air_date: "2019-11-12",
    genre_ids: [10765, 10759, 18],
    id: 82856,
    name: "The Mandalorian",
    original_name: "The Mandalorian",
    overview:
      "En el anárquico período tras el hundimiento del Imperio Galáctico, un cazarrecompensas con armadura conocido solo como El Mandaloriano emprende una misión bien remunerada aunque enigmática.",
    poster_path: "/mzzZKJ4fvwib8Fty1tv4Vtp9R0b.jpg",
    vote_average: 8.5,
  },
  {
    backdrop_path: "/qcpC9lv6VLL4Zw45EveYELyje1w.jpg",
    first_air_date: "2020-10-05",
    genre_ids: [18, 10766, 10751],
    id: 111453,
    name: "घुम है किसिकी प्यार में",
    original_name: "घुम है किसिकी प्यार में",
    overview: "",
    poster_path: "/uNjnoT3RChs2r7O9pDyx7TNBvIj.jpg",
    vote_average: 5.8,
  },
  {
    backdrop_path: "/ymkFaEO0UdYXKIgcWZ23TlYIRD9.jpg",
    first_air_date: "2020-11-16",
    genre_ids: [18, 10766, 10751],
    id: 113218,
    name: "Imlie",
    original_name: "इमली",
    overview:
      "Todo lo que Imlie quería era crearse un nombre en la ciudad. Pero a su llegada, se encuentra atrapada en medio de la historia de amor de Aditya y Malini.",
    poster_path: "/brajFHvqeitbp7ifevWpFpirS4S.jpg",
    vote_average: 5.6,
  },
  {
    backdrop_path: "/mAJ84W6I8I272Da87qplS2Dp9ST.jpg",
    first_air_date: "2023-01-23",
    genre_ids: [9648, 18],
    id: 202250,
    name: "Dirty Linen",
    original_name: "Dirty Linen",
    overview: "",
    poster_path: "/ujlkQtHAVShWyWTloGU2Vh5Jbo9.jpg",
    vote_average: 4.9,
  },
  {
    backdrop_path: "/gQxaF79LUTtopdYHsuS8lUr9rvF.jpg",
    first_air_date: "2021-11-14",
    genre_ids: [18, 80],
    id: 97951,
    name: "Mayor of Kingstown",
    original_name: "Mayor of Kingstown",
    overview:
      "Ambientada en una pequeña ciudad de Michigan donde la única industria que queda son las cárceles federales, estatales y privadas, la historia sigue a la familia McClusky, los intermediarios del poder entre la policía, los delincuentes, los presos, los guardias de prisiones y los políticos, en una ciudad completamente dependiente de las prisiones.  y los prisioneros que contienen.",
    poster_path: "/s18V51BeLOr9vB0rXm3QcVS6wwL.jpg",
    vote_average: 8.2,
  },
  {
    backdrop_path: "/26be9JndZG6uYBfNPAy51dUKj0y.jpg",
    first_air_date: "2022-01-03",
    genre_ids: [10766],
    id: 154571,
    name: "Quero é Viver",
    original_name: "Quero é Viver",
    overview: "",
    poster_path: "/bAp4W1ppwVlp7EpJb91RwTTLhm3.jpg",
    vote_average: 6.4,
  },
  {
    backdrop_path: "/1vgdmeW6keP47DQ1tGwfVCdUKqu.jpg",
    first_air_date: "2020-10-12",
    genre_ids: [35],
    id: 111551,
    name: "Χαιρέτα μου τον Πλάτανο",
    original_name: "Χαιρέτα μου τον Πλάτανο",
    overview: "",
    poster_path: "/vAu6or1W4G1q7wJxQfDmATtnIg.jpg",
    vote_average: 5.5,
  },
  {
    backdrop_path: null,
    first_air_date: "",
    genre_ids: [35],
    id: 213017,
    original_language: "it",
    original_name: "Lo Zoo di 105",
    overview: "",
    poster_path: "/6KL71OV5wHQGk5KZMP3qp7Mj5HA.jpg",
    vote_average: 3.7,
  },
  {
    backdrop_path: "/caGVr9Il2gj8bN4ow6qsLm60TxM.jpg",
    first_air_date: "2005-03-27",
    genre_ids: [18],
    id: 1416,
    name: "Anatomía de Grey",
    original_name: "Grey's Anatomy",
    overview:
      "La vida de Meredith Grey no es nada fácil. Intenta tomar las riendas de su vida, aunque su trabajo sea de esos que te hacen la vida imposible. Meredith es una cirujana interna de primer año en el Hospital Grace de Seattle, el programa de prácticas más duro de la Facultad de Medicina de Harvard. Y ella lo va a comprobar. Pero no estará sola. Un elenco de compañeros de promoción tendrán que superar la misma prueba. Ahora están en el mundo real, son doctores del hospital. Y en un mundo donde la experiencia en el trabajo puede ser un factor de vida o muerte, todos ellos tendrán que lidiar con los altibajos de sus vidas personales.",
    poster_path: "/jPzW61WlkyHVdvm8dCQZveTvmgW.jpg",
    vote_average: 8.3,
  },
  {
    backdrop_path: "/zJNEXWx3YyWGQioCbutFd5dcNYS.jpg",
    first_air_date: "2022-03-21",
    genre_ids: [10766, 10759, 10751],
    id: 157059,
    name: "Poliana Moça",
    original_name: "Poliana Moça",
    overview: "",
    poster_path: "/sSRFeVwpyUffmqvreVbbNILHYbY.jpg",
    vote_average: 6.5,
  },
  {
    backdrop_path: "/jIV5weV19wH02rnuWyMtYI4dYC8.jpg",
    first_air_date: "2023-02-13",
    genre_ids: [10759, 35, 18],
    id: 215803,
    name: "Batang Quiapo",
    original_name: "Batang Quiapo",
    overview: "",
    poster_path: "/9McqS8mgMf5NJCAKZIY6J1oOl8y.jpg",
    vote_average: 7.5,
  },
  {
    backdrop_path: "/gFkHcIh7iE5G0oVOgpmY8ONQjhl.jpg",
    first_air_date: "2014-10-07",
    genre_ids: [18, 10765],
    id: 60735,
    name: "The Flash",
    original_name: "The Flash",
    overview:
      "Después de que un acelerador de partículas cause una extraña tormenta, al investigador científico de la policía, Barry Allen, le cae un rayo y entra en coma. Meses después despierta con el poder de moverse a súper velocidad permitiéndole ser el ángel de la guardia de Central City. Aunque al principio se siente entusiasmado con sus nuevos poderes, Barry descubre que no es el único “meta-humano” que se originó tras la explosión del acelerador – y no todo el mundo está usando sus nuevos poderes para el bien. Los compañeros del laboratorio STAR dedican su vida a ayudar a Barry a proteger a los inocentes. Por ahora, solo algunos amigos cercanos saben que Barry es, literalmente, el hombre más rápido del mundo, pero no pasará mucho hasta que el mundo conozca que ahora Barry Allen es … Flash.",
    poster_path: "/7ci4qqkBJorLxSBwTj28vwh0bU.jpg",
    vote_average: 7.8,
  },
];

